package corbaServer.corba;


/**
* corbaServer/corba/corbaServerRehearsalDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/SoNia/workspace/RehearsalReservationCore/idl/corbaServer.idl
* viernes 9 de abril de 2010 17H44' CEST
*/

public final class corbaServerRehearsalDTO implements org.omg.CORBA.portable.IDLEntity
{
  
	private static final long serialVersionUID = 1L;
public String operaName = null;
  public String date = null;
  public int seats = (int)0;

  public corbaServerRehearsalDTO ()
  {
  } // ctor

  public corbaServerRehearsalDTO (String _operaName, String _date, int _seats)
  {
    operaName = _operaName;
    date = _date;
    seats = _seats;
  } // ctor

} // class corbaServerRehearsalDTO
