package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/CorbaServer.idl
* sábado 13 de marzo de 2010 16H41' CET
*/


//Interface for the CORBA Server
public interface ICorbaServerOperations 
{
  corbaServer.corba.corbaServerRehearsalDTO[] getRehearsals () throws corbaServer.corba.DBErrorException;
} // interface ICorbaServerOperations
