package corbaServer.corba;


/**
* corbaServer/corba/corbaServerRehearsalDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/corbaServer.idl
* domingo 7 de marzo de 2010 22H29' CET
*/

public final class corbaServerRehearsalDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String operaName = null;
  public String date = null;
  public int seats = (int)0;

  public corbaServerRehearsalDTO ()
  {
  } // ctor

  public corbaServerRehearsalDTO (String _operaName, String _date, int _seats)
  {
    operaName = _operaName;
    date = _date;
    seats = _seats;
  } // ctor

} // class corbaServerRehearsalDTO
