package corbaServer.corba;


/**
* corbaServer/corba/DBErrorException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/CorbaServer.idl
* sábado 13 de marzo de 2010 16H41' CET
*/

public final class DBErrorException extends org.omg.CORBA.UserException
{
  public String message = null;
  public String description = null;

  public DBErrorException ()
  {
    super(DBErrorExceptionHelper.id());
  } // ctor

  public DBErrorException (String _message, String _description)
  {
    super(DBErrorExceptionHelper.id());
    message = _message;
    description = _description;
  } // ctor


  public DBErrorException (String $reason, String _message, String _description)
  {
    super(DBErrorExceptionHelper.id() + "  " + $reason);
    message = _message;
    description = _description;
  } // ctor

} // class DBErrorException
