package corbaServer.corba;

/**
* corbaServer/corba/DBErrorExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Programacion/TuttoVerdi/RehearsalReservationCore/idl/corbaServer.idl
* domingo 2 de mayo de 2010 13H32' CEST
*/

public final class DBErrorExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaServer.corba.DBErrorException value = null;

  public DBErrorExceptionHolder ()
  {
  }

  public DBErrorExceptionHolder (corbaServer.corba.DBErrorException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaServer.corba.DBErrorExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaServer.corba.DBErrorExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaServer.corba.DBErrorExceptionHelper.type ();
  }

}
