package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Programacion/TuttoVerdi/RehearsalReservationCore/idl/corbaServer.idl
* sábado 8 de mayo de 2010 10H35' CEST
*/


//Interface for the CORBA Server
public interface ICorbaServer extends ICorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaServer
