package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/SoNia/workspace/RehearsalReservationCore/idl/corbaServer.idl
* viernes 9 de abril de 2010 17H44' CEST
*/


//Interface for the CORBA Server
public interface ICorbaServer extends ICorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaServer
