package corbaServer.corba;


/**
* corbaServer/corba/ICorbaServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/corbaServer.idl
* domingo 7 de marzo de 2010 22H29' CET
*/


//Interface for the CORBA Server
public interface ICorbaServer extends ICorbaServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaServer
